version: "2.2"

services:
  latex:
    build: .
    ports:
      - 1337:1337
    volumes:
      - ./srv:/srv:ro
      - storage:/storage
    depends_on:
      - mariadb
  redis:
    image: redis
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: lamp
    volumes:
      - db:/var/lib/mysql

volumes:
    storage:
    db:

networks:
  default:
    enable_ipv6: true
    ipam:
        driver: default
        config:
            - subnet: "fd42:d0ce:7777::/64"